# frozen_string_literal: true

require "erb"

module ModelSettings
  module Documentation
    # HTML formatter for settings documentation
    #
    # Generates clean, semantic HTML documentation suitable for:
    # - Internal wikis
    # - Documentation sites
    # - README embeds
    # - Browser viewing
    #
    # The HTML is deliberately minimal and semantic, allowing custom styling
    # via CSS.
    #
    # @example
    #   formatter = HtmlFormatter.new(User, User._settings)
    #   html = formatter.generate
    #   File.write("docs/user_settings.html", html)
    #
    class HtmlFormatter
      attr_reader :model_class, :settings

      def initialize(model_class, settings)
        @model_class = model_class
        @settings = settings
      end

      # Generate HTML documentation
      #
      # @return [String] HTML documentation
      def generate
        html = []
        html << html_header
        html << html_body
        html << html_footer
        html.join("\n")
      end

      private

      # Generate HTML header
      #
      # @return [String] HTML header
      def html_header
        <<~HTML
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>#{escape_html(model_class.name)} Settings Documentation</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                line-height: 1.6;
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
                color: #333;
              }
              h1 { border-bottom: 2px solid #e1e4e8; padding-bottom: 10px; }
              h2 { margin-top: 24px; border-bottom: 1px solid #e1e4e8; padding-bottom: 6px; }
              h3 { margin-top: 16px; }
              .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
              .setting { margin: 20px 0; padding: 16px; border: 1px solid #e1e4e8; border-radius: 6px; }
              .setting h3 { margin-top: 0; }
              .setting-header { display: flex; justify-content: space-between; align-items: center; }
              .badge { display: inline-block; padding: 2px 8px; font-size: 12px; border-radius: 3px; }
              .badge-deprecated { background-color: #ffeaa7; color: #d63031; }
              .badge-type { background-color: #74b9ff; color: #0984e3; }
              table { width: 100%; border-collapse: collapse; margin: 12px 0; }
              th, td { text-align: left; padding: 8px; border-bottom: 1px solid #e1e4e8; }
              th { font-weight: 600; background-color: #f6f8fa; }
              code { background-color: #f6f8fa; padding: 2px 6px; border-radius: 3px; font-size: 90%; }
              pre { background-color: #f6f8fa; padding: 16px; border-radius: 6px; overflow-x: auto; }
              .nested { margin-left: 20px; padding-left: 20px; border-left: 3px solid #e1e4e8; }
              .description { margin: 12px 0; }
              .api-methods { background-color: #f6f8fa; padding: 12px; border-radius: 6px; margin: 12px 0; }
              .callbacks, .cascade, .sync { margin: 12px 0; }
            </style>
          </head>
          <body>
        HTML
      end

      # Generate HTML body
      #
      # @return [String] HTML body
      def html_body
        html = []

        html << "<h1>#{escape_html(model_class.name)} Settings Documentation</h1>"
        html << "<div class=\"meta\">"
        html << "  <strong>Generated:</strong> #{Time.current.strftime("%Y-%m-%d %H:%M:%S %Z")}<br>"
        html << "  <strong>ModelSettings Version:</strong> #{escape_html(ModelSettings::VERSION)}<br>"
        html << "  <strong>Total Settings:</strong> #{settings.size}"
        html << "</div>"

        settings.each do |setting|
          html << format_setting_html(setting)
        end

        html.join("\n")
      end

      # Generate HTML footer
      #
      # @return [String] HTML footer
      def html_footer
        <<~HTML
            <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e4e8; color: #666; font-size: 14px;">
              <p>Generated by ModelSettings v#{escape_html(ModelSettings::VERSION)}</p>
            </footer>
          </body>
          </html>
        HTML
      end

      # Format a single setting as HTML
      #
      # @param setting [Setting] The setting to format
      # @param level [Integer] Nesting level
      # @return [String] HTML for the setting
      def format_setting_html(setting, level = 2)
        html = []
        html << "<div class=\"setting\">"

        # Header with name and badges
        html << "  <div class=\"setting-header\">"
        html << "    <h#{level + 1}><code>#{escape_html(setting.name.to_s)}</code></h#{level + 1}>"
        html << "    <div>"
        html << "      <span class=\"badge badge-type\">#{escape_html(setting.type.to_s)}</span>"
        if setting.deprecated?
          html << "      <span class=\"badge badge-deprecated\">Deprecated</span>"
        end
        html << "    </div>"
        html << "  </div>"

        # Description
        if setting.description
          html << "  <div class=\"description\">#{escape_html(setting.description)}</div>"
        end

        # Properties table
        html << "  <table>"
        html << "    <tr><th>Property</th><th>Value</th></tr>"
        html << "    <tr><td>Type</td><td><code>#{escape_html(setting.type.to_s)}</code></td></tr>"
        html << "    <tr><td>Storage</td><td><code>#{escape_html(format_storage(setting))}</code></td></tr>"

        if setting.options.key?(:default)
          html << "    <tr><td>Default</td><td><code>#{escape_html(format_value(setting.default))}</code></td></tr>"
        end

        # Authorization
        if (auth_info = format_authorization(setting))
          html << "    <tr><td>Authorization</td><td>#{escape_html(auth_info)}</td></tr>"
        end

        # Deprecation
        if setting.deprecated?
          dep_msg = setting.options[:deprecated]
          dep_msg = "Yes" if dep_msg == true
          html << "    <tr><td>Deprecated</td><td>⚠️  #{escape_html(dep_msg)}</td></tr>"
        end

        html << "  </table>"

        # API Methods
        html << "  <div class=\"api-methods\">"
        html << "    <strong>API Methods:</strong>"
        html << "    <pre><code>"
        html << "# Getter\n#{escape_html(model_class.name.underscore)}.#{escape_html(setting.name.to_s)}\n\n"
        html << "# Setter\n#{escape_html(model_class.name.underscore)}.#{escape_html(setting.name.to_s)} = value\n\n"
        html << "# Helpers (for boolean settings)\n"
        html << "#{escape_html(model_class.name.underscore)}.#{escape_html(setting.name.to_s)}_enable!\n"
        html << "#{escape_html(model_class.name.underscore)}.#{escape_html(setting.name.to_s)}_disable!\n"
        html << "#{escape_html(model_class.name.underscore)}.#{escape_html(setting.name.to_s)}_toggle!\n"
        html << "#{escape_html(model_class.name.underscore)}.#{escape_html(setting.name.to_s)}_enabled?\n"
        html << "#{escape_html(model_class.name.underscore)}.#{escape_html(setting.name.to_s)}_disabled?"
        html << "</code></pre>"
        html << "  </div>"

        # Cascades
        if setting.options[:cascade]
          html << format_cascade_html(setting)
        end

        # Syncs
        if setting.options[:sync]
          html << format_sync_html(setting)
        end

        # Callbacks
        callbacks = extract_callbacks(setting)
        if callbacks.any?
          html << format_callbacks_html(callbacks)
        end

        # Metadata
        if setting.metadata.any?
          html << format_metadata_html(setting.metadata)
        end

        # Nested settings
        if setting.children.any?
          html << "  <h#{level + 2}>Nested Settings</h#{level + 2}>"
          html << "  <div class=\"nested\">"
          setting.children.each do |child|
            html << format_setting_html(child, level + 1)
          end
          html << "  </div>"
        end

        html << "</div>"
        html.join("\n")
      end

      # Format cascade configuration as HTML
      #
      # @param setting [Setting] The setting
      # @return [String] HTML
      def format_cascade_html(setting)
        cascade = setting.options[:cascade]
        html = []
        html << "<div class=\"cascade\">"
        html << "  <strong>Cascades:</strong>"
        html << "  <ul>"
        html << "    <li>Enable: #{cascade[:enable] ? "Yes" : "No"}</li>" if cascade.key?(:enable)
        html << "    <li>Disable: #{cascade[:disable] ? "Yes" : "No"}</li>" if cascade.key?(:disable)
        html << "  </ul>"
        html << "</div>"
        html.join("\n")
      end

      # Format sync configuration as HTML
      #
      # @param setting [Setting] The setting
      # @return [String] HTML
      def format_sync_html(setting)
        sync = setting.options[:sync]
        target = sync[:target] || sync["target"]
        mode = sync[:mode] || sync["mode"] || :forward

        html = []
        html << "<div class=\"sync\">"
        html << "  <strong>Sync:</strong> "
        html << "  <code>#{escape_html(setting.name.to_s)}</code> → "
        html << "  <code>#{escape_html(target.to_s)}</code> "
        html << "  (#{escape_html(mode.to_s)})"
        html << "</div>"
        html.join("\n")
      end

      # Format callbacks as HTML
      #
      # @param callbacks [Hash] Callbacks hash
      # @return [String] HTML
      def format_callbacks_html(callbacks)
        html = []
        html << "<div class=\"callbacks\">"
        html << "  <strong>Callbacks:</strong>"
        html << "  <ul>"
        callbacks.each do |name, callback|
          html << "    <li><code>#{escape_html(name)}</code>: #{escape_html(callback.to_s)}</li>"
        end
        html << "  </ul>"
        html << "</div>"
        html.join("\n")
      end

      # Format metadata as HTML
      #
      # @param metadata [Hash] Metadata hash
      # @return [String] HTML
      def format_metadata_html(metadata)
        html = []
        html << "<div class=\"metadata\">"
        html << "  <strong>Metadata:</strong>"
        html << "  <table>"
        metadata.each do |key, value|
          html << "    <tr><td><code>#{escape_html(key.to_s)}</code></td><td>#{escape_html(value.to_s)}</td></tr>"
        end
        html << "  </table>"
        html << "</div>"
        html.join("\n")
      end

      # Escape HTML special characters
      #
      # @param text [String] Text to escape
      # @return [String] Escaped text
      def escape_html(text)
        text.to_s
          .gsub("&", "&amp;")
          .gsub("<", "&lt;")
          .gsub(">", "&gt;")
          .gsub('"', "&quot;")
          .gsub("'", "&#39;")
      end

      # Format storage configuration
      #
      # @param setting [Setting] The setting
      # @return [String] Storage info
      def format_storage(setting)
        case setting.type
        when :column
          "#{setting.name} column"
        when :json, :store_model
          if setting.storage.is_a?(Hash)
            "#{setting.storage[:column]} column"
          else
            "inherited"
          end
        else
          "unknown"
        end
      end

      # Format value for display
      #
      # @param value [Object] The value
      # @return [String] Formatted value
      def format_value(value)
        case value
        when Symbol
          ":#{value}"
        when String
          "\"#{value}\""
        when nil
          "nil"
        when Hash
          value.inspect
        when Array
          value.inspect
        else
          value.to_s
        end
      end

      # Format authorization info
      #
      # @param setting [Setting] The setting
      # @return [String, nil] Authorization info
      def format_authorization(setting)
        if setting.options[:policy]
          "Policy: #{setting.options[:policy]} (action: update_#{setting.name}?)"
        elsif setting.options[:roles]
          roles = Array(setting.options[:roles]).map(&:to_s).join(", ")
          "Roles: #{roles}"
        end
      end

      # Extract callbacks from setting
      #
      # @param setting [Setting] The setting
      # @return [Hash] Callbacks hash
      def extract_callbacks(setting)
        callbacks = {}

        %i[
          before_enable after_enable around_enable
          before_disable after_disable around_disable
          before_toggle after_toggle
          before_change after_change around_change
          after_change_commit
          validate_with
        ].each do |callback_name|
          next unless setting.options.key?(callback_name)

          callback = setting.options[callback_name]
          callbacks[callback_name] = format_callback(callback)
        end

        callbacks
      end

      # Format callback for display
      #
      # @param callback [Symbol, Proc, Array] The callback
      # @return [String] Formatted callback
      def format_callback(callback)
        case callback
        when Symbol
          ":#{callback}"
        when Proc
          "Proc"
        when Array
          callback.map { |cb| format_callback(cb) }.join(", ")
        else
          callback.to_s
        end
      end
    end
  end
end
