name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
        rails:
          - '6.1'
          - '7.0'
          - '7.1'
          - '8.0'
        exclude:
          # Rails 7.1 requires Ruby 3.1+
          - ruby: '3.0'
            rails: '7.1'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          RAILS_VERSION: ${{ matrix.rails }}
      - name: Run the default task
        run: bundle exec rake
